"""Projection: derive the engine-native view from a Partition (D-179).

⭐ DERIVATION, not authorship: the Partition is the source of truth, this view
is regenerated by the kit and never hand-edited (I-178 / I-196 r1).

Guard-fences from the meta return (2026-08-22):
1. Renvois conditionnels = POTENTIAL for the Director — emitted as `links`,
   NEVER as auto-triggers (a naive "go to N → trigger" would reinstall the
   railroad through plumbing, D-065). Exceptions report counts both families.
2. World conditions (conséquences du monde) = native scripting — entries
   carrying `triggers_all` keywords (D-119), finally using the dormant fields.
3. hidden = routing, not deletion — secrets keep porteurs/triggers so what the
   character KNOWS can still surface (D-110); the camera stays perception.
"""
from __future__ import annotations

import json
from pathlib import Path

from coderain.memory import Library, MemoryStore
from coderain.profiles import Entry

from .aval import _split_front, get_record


def _load_node_ids(partition_dir: Path) -> list[dict]:
    p = Path(partition_dir)
    out = []
    for f in sorted((p / "nodes").glob("*.md")):
        front, body = _split_front(f.read_text(encoding="utf-8"))
        try:
            meta = json.loads(front)
        except json.JSONDecodeError:
            continue
        meta["_body"] = body
        out.append(meta)
    return out


def derive(partition_dir: Path, root_dir: Path, save_slug: str,
           corpus_dir: Path) -> dict:
    """Upsert engine-native entries derived from the Partition into the save.
    Idempotent: same partition + same save = same derived view."""
    partition_dir = Path(partition_dir)
    lib = Library(root_dir)
    store: MemoryStore = lib.saves.store(save_slug)

    nodes = _load_node_ids(partition_dir)
    counts = {"nodes": 0, "records": 0, "conditions": 0}

    # 1) nodes → locations registry, linked by slugs (potential, no triggers)
    for meta in nodes:
        liens = [str(l["cible_id"]) for l in meta.get("liens", [])]
        store.upsert_entry("locations.md", Entry(
            title=f"{meta.get('titre', meta['id'])}",
            slug=meta["id"],
            attrs={"links": ", ".join(liens),
                   "altitude": str(meta.get("altitude", "scene"))},
            body=meta["_body"]))
        counts["nodes"] += 1

    # 2) records → characters registry, transverses in body (D-113/D-119)
    recs = sorted((partition_dir / "records").glob("*.md"))
    for f in recs:
        from .aval import get_record
        rec = get_record(partition_dir, f.stem)
        tr = rec["meta"].get("transverse") or {}
        body = json.dumps(rec["stats"], ensure_ascii=False, indent=1)
        if tr:
            body += "\n\n" + "\n".join(f"- {k}: {v}" for k, v in tr.items())
        store.upsert_entry("characters.md", Entry(
            title=str(rec["meta"].get("nom", rec["meta"]["id"])),
            slug=rec["meta"]["id"],
            attrs={"importance": "4"} if rec["meta"].get("classe") == "creature"
            else {},
            body=body))
        counts["records"] += 1

    # 3) world conditions → scripting-native entries (triggers_all, D-119);
    #    keywords are authored (deterministic), never guessed from prose
    av_path = partition_dir / "aventure.md"
    if av_path.exists():
        front, _body = _split_front(av_path.read_text(encoding="utf-8"))
        meta = json.loads(front) if front else {}
        for i, cond in enumerate(meta.get("conditions", [])):
            store.upsert_entry("locations.md", Entry(
                title=f"Condition de monde #{i + 1}",
                slug=f"cond-monde-{i + 1}",
                attrs={"triggers_all": ", ".join(cond.get("triggers_all", []))
                       or cond.get("declencheur", ""),
                       "weight": "heavy"},
                body=str(cond.get("description_md", ""))))
            counts["conditions"] += 1

    # 4) secrets → hidden entries with porteurs kept visible to routing (D-019)
    for f in sorted((partition_dir / "secrets").glob("*.md")):
        front, body = _split_front(f.read_text(encoding="utf-8"))
        try:
            meta = json.loads(front)
        except json.JSONDecodeError:
            continue
        store.upsert_entry("characters.md", Entry(
            title=str(meta.get("id")), slug=str(meta.get("id")),
            attrs={"hidden": "true", "weight": "critical",
                   "triggers_all": ", ".join(meta.get("porteurs", []))},
            body=str(body)))
        counts.setdefault("secrets", 0)
        counts["secrets"] += 1

    # 5) directing brief → custom instructions of the save (always assembled,
    #    small and stable); idempotent via markers
    brief = partition_dir / "directeur.md"
    ci_path = Path(lib.saves.dir(save_slug)) / "custom-instructions.md"
    if brief.exists():
        marker_start = "<!-- P4-BRIEF-START -->"
        marker_end = "<!-- P4-BRIEF-END -->"
        text = ci_path.read_text(encoding="utf-8")
        if marker_start not in text:
            block = (f"\n{marker_start}\n{brief.read_text(encoding='utf-8')}\n"
                     f"{marker_end}\n")
            ci_path.write_text(text + block, encoding="utf-8")

    # 6) pointer initialization: position only (D-180), never lived experience
    state_p = Path(lib.saves.dir(save_slug)) / "state.json"
    if state_p.exists() and nodes:
        playable = next((n for n in nodes
                         if n["id"].startswith("para-")), nodes[0])
        state = json.loads(state_p.read_text(encoding="utf-8"))
        if not state.get("location"):
            state["location"] = playable["id"]
            state_p.write_text(json.dumps(state, ensure_ascii=False, indent=1),
                               encoding="utf-8")

    return counts
