"""Projection: derive the engine-native view from a Partition (D-179).

⭐ DERIVATION, not authorship: the Partition is the source of truth, this view
is regenerated by the kit and never hand-edited (I-178 / I-196 r1).

Guard-fences from the meta return (2026-08-22):
1. Renvois conditionnels = POTENTIAL for the Director — emitted as `links`,
   NEVER as auto-triggers (a naive "go to N → trigger" would reinstall the
   railroad through plumbing, D-065). Exceptions report counts both families.
2. World conditions (conséquences du monde) = native scripting — entries
   carrying `triggers_all` keywords (D-119), finally using the dormant fields.
3. hidden = routing, not deletion — secrets keep porteurs/triggers so what the
   character KNOWS can still surface (D-110); the camera stays perception.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from coderain.memory import Library, MemoryStore
from coderain.profiles import Entry
from coderain import validator as validator_mod

from .aval import _split_front, get_record


def _load_node_ids(partition_dir: Path) -> list[dict]:
    p = Path(partition_dir)
    out = []
    for f in sorted((p / "nodes").glob("*.md")):
        front, body = _split_front(f.read_text(encoding="utf-8"))
        try:
            meta = json.loads(front)
        except json.JSONDecodeError:
            continue
        meta["_body"] = body
        out.append(meta)
    return out


def _strip_sequences(body: str) -> str:
    """Remove every '… go to N' / 'Go to N!' line from a node body — including
    PDF-wrapped variants ('Go to \\n17.') and the dangling conditional
    fragment left on the previous line ('If you decide to explore the cave,').
    The structured `liens` carry the potential; sequences never survive."""
    lines = body.splitlines()
    seq = re.compile(r"(?i)go to\s*\d{1,3}\s*[.!]?")
    tail = re.compile(r"(?i)\bgo to\s*$")
    num = re.compile(r"^\s*\d{1,3}\s*[.!]?\s*$")
    drop = set()
    for i, line in enumerate(lines):
        if seq.search(line):
            drop.add(i)
        elif tail.search(line) and i + 1 < len(lines) and num.match(lines[i + 1]):
            drop.add(i)
            drop.add(i + 1)
    for i in sorted(drop):
        j = i - 1
        while j >= 0 and j not in drop and (
                re.search(r"[,!]\s*$", lines[j])
                or re.match(r"\s*(?:or, )?if\b", lines[j], re.I)):
            drop.add(j)
            break
    return "\n".join(l for k, l in enumerate(lines) if k not in drop)


def derive(partition_dir: Path, root_dir: Path, save_slug: str,
           corpus_dir: Path) -> dict:
    """Upsert engine-native entries derived from the Partition into the save.
    Idempotent: same partition + same save = same derived view."""
    partition_dir = Path(partition_dir)
    lib = Library(root_dir)
    store: MemoryStore = lib.saves.store(save_slug)

    nodes = _load_node_ids(partition_dir)
    counts = {"nodes": 0, "records": 0, "conditions": 0}

    # 1) nodes → locations registry. ⛔ PAS d'attribut `links`: il ferait
    #    co-assembler les scènes suivantes avec la scène courante — or le
    #    corpus non atteint doit être PHYSIQUEMENT INERTIE dans le contexte
    #    (SPEC-MVP critique 1). Le routage reste dans la partition
    #    (front-matter des nodes): le Director le lit par outil, à la
    #    transition, jamais d'avance.
    for meta in nodes:
        body = _strip_sequences(meta["_body"]).strip()
        store.upsert_entry("locations.md", Entry(
            title=f"{meta.get('titre', meta['id'])}",
            slug=meta["id"],
            attrs={"altitude": str(meta.get("altitude", "scene")),
                   "weight": "light"},
            body=body))
        counts["nodes"] += 1

    # 2) records → characters registry, transverses in body (D-113/D-119)
    recs = sorted((partition_dir / "records").glob("*.md"))
    for f in recs:
        from .aval import get_record
        rec = get_record(partition_dir, f.stem)
        tr = rec["meta"].get("transverse") or {}
        body = json.dumps(rec["stats"], ensure_ascii=False, indent=1)
        if tr:
            body += "\n\n" + "\n".join(f"- {k}: {v}" for k, v in tr.items())
        store.upsert_entry("characters.md", Entry(
            title=str(rec["meta"].get("nom", rec["meta"]["id"])),
            slug=rec["meta"]["id"],
            attrs={"importance": "4"} if rec["meta"].get("classe") == "creature"
            else {},
            body=body))
        counts["records"] += 1

    # 3) world conditions → scripting-native entries (triggers_all, D-119);
    #    keywords are authored (deterministic), never guessed from prose
    av_path = partition_dir / "aventure.md"
    if av_path.exists():
        front, _body = _split_front(av_path.read_text(encoding="utf-8"))
        meta = json.loads(front) if front else {}
        for i, cond in enumerate(meta.get("conditions", [])):
            dec = cond.get("declencheur") or {}
            dec_txt = (str(dec.get("valeur", "")) if isinstance(dec, dict)
                       else str(dec))
            store.upsert_entry("locations.md", Entry(
                title=f"Condition de monde #{i + 1}",
                slug=str(cond.get("id") or f"cond-monde-{i + 1}"),
                attrs={"triggers_all": ", ".join(cond.get("triggers_all", []))
                       or dec_txt,
                       "weight": "heavy"},
                body=str(cond.get("description_md", ""))))
            counts["conditions"] += 1
        # trajectoire par défaut (D-120) — POTENTIEL pour le Director,
        # jamais auto-déclenchée (garde anti-rail): chaque événement porte
        # ses perturbations et l'état qui les déclenche
        for ev in meta.get("trajectoire", []):
            perts = "; ".join(
                f"{p.get('condition_etat', '?')} ⇒ {p.get('issue', 'issue?')}"
                for p in ev.get("perturbations", [])) or "(aucune fournie)"
            store.upsert_entry("locations.md", Entry(
                title=f"Trajectoire #{ev.get('id', '?')}",
                slug=str(ev.get("id") or f"traj-{ev.get('id', '?')}"),
                attrs={"weight": "heavy",
                       "once": str(ev.get("once", True)).lower(),
                       "triggers_all": (
                           (ev.get("declencheur") or {}).get("valeur", "")
                           if isinstance(ev.get("declencheur"), dict)
                           else str(ev.get("declencheur", "")))},
                body=(f"{ev.get('description_md', '')}\n\nPerturbations: "
                      f"{perts}")))
            counts.setdefault("trajectoire", 0)
            counts["trajectoire"] += 1

    # 4) secrets → hidden entries with porteurs kept visible to routing (D-019)
    for f in sorted((partition_dir / "secrets").glob("*.md")):
        front, body = _split_front(f.read_text(encoding="utf-8"))
        try:
            meta = json.loads(front)
        except json.JSONDecodeError:
            continue
        store.upsert_entry("characters.md", Entry(
            title=str(meta.get("id")), slug=str(meta.get("id")),
            attrs={"hidden": "true", "weight": "critical",
                   "triggers_all": ", ".join(meta.get("porteurs", []))},
            body=str(body)))
        counts.setdefault("secrets", 0)
        counts["secrets"] += 1

    # 5) directing brief → custom instructions of the save (always assembled,
    #    small and stable); the marked block is REPLACED on re-projection so
    #    an updated brief reaches existing saves
    brief = partition_dir / "directeur.md"
    ci_path = Path(lib.saves.dir(save_slug)) / "custom-instructions.md"
    if brief.exists():
        marker_start = "<!-- P4-BRIEF-START -->"
        marker_end = "<!-- P4-BRIEF-END -->"
        block = (f"{marker_start}\n{brief.read_text(encoding='utf-8')}\n"
                 f"{marker_end}\n")
        text = ci_path.read_text(encoding="utf-8")
        i, j = text.find(marker_start), text.find(marker_end)
        if i >= 0 and j > i:
            text = text[:i] + block + text[j + len(marker_end):]
        else:
            text = text + "\n" + block
        ci_path.write_text(text, encoding="utf-8")

    # 6) pointer initialization: position only (D-180), never lived experience
    state_p = Path(lib.saves.dir(save_slug)) / "state.json"
    if state_p.exists() and nodes:
        playable = next((n for n in nodes
                         if n["id"].startswith("para-")), nodes[0])
        state = json.loads(state_p.read_text(encoding="utf-8"))
        if not validator_mod.current_location(state):
            # Issue #219 : une seule source — `player.location` — voir
            # `validator.current_location()`. Le guichet `apply_world`
            # applique la même règle.
            player = state.setdefault("player", {})
            if isinstance(player, dict):
                player["location"] = playable["id"]
            state_p.write_text(json.dumps(state, ensure_ascii=False, indent=1),
                               encoding="utf-8")

    return counts
